### ISSUE TITLE
Defining the base point and creating the ROMs?

### ISSUE THREAD

**Issue by likewise** [kazkojima/x25519-fpga#1]
What is the chosen base point, and can it be changed?
Also, how are the ROM files generated, it is not clear for me?

My interest is in porting this to different FPGAs, such as Intel/Altera and AMD/Xilinx.

**Comment by kazkojima** [comment]
Hi,

Those pre-computed tables could be easily generated with existing x25519 programs.
I've added gen_precomp_25519() function to jl/x25519.jl to regenerate precomputed tables with julia language. You can change the base point with modifying BasePoint_25519 in jl/x25519.jl too. The commands below

```
$ cd x25519-fpga/jl
$ julia
julia> include("x25519.jl")
julia> gen_precomp_25519()
```
should regenerate pre-computed table files x25519/*_precomp_32k.dat. Hope this helps.

**Comment by likewise** [comment]
Thank you very much. I will have a look at that.
